# You are given two strings s and t.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Return the letter that was added to t.

# split the string 
# set up a while loop
# compare until one string runs out then print that last char.

# def difference(s, t)
#   arr1 = s.split("")
#   arr2 = t.split("")
#   # i = 0
#   if arr1.length == arr2.length
#     p arr1
#   else
#     p arr2[-1]
#   end
# end

# p difference("abcd", "abcde")